/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface LlamaInvocation {
  nThreads: number
  nTokPredict: number
  topK: number
  topP: number
  temp: number
  repeatPenalty: number
  stopSequence: string
  prompt: string
}
export interface LlamaContextParams {
  nCtx: number
  nParts: number
  seed: number
  f16Kv: boolean
  logitsAll: boolean
  vocabOnly: boolean
  useMlock: boolean
  embedding: boolean
}
export class LLamaContext { }
export class LLama {
  static new(path: string, params?: LlamaContextParams | undefined | null): LLama
  run(input: LlamaInvocation, callback: (...args: any[]) => any): void
}
