[package]
name = "common-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
once_cell = "1.17.1"
time = { version = "0.3.21", features = ["macros", "local-offset", "formatting", "parsing"] }
console = "0.15.5"